# Publish all joint states -----------------------------------
m3d_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  
  
# Position Controllers ---------------------------------------
m3d_joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: m3d_rot_laser_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

