<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="m3d_unit" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="10" /> <!-- arbitrary value for mass -->
  <xacro:property name="box_height" value="0.2" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="box_width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="box_depth" value="0.2" /> <!-- Square dimensions (widthxwidth) of beams -->
  
  <xacro:macro name="m3d_unit">


  <!-- Constants for robot dimensions -->


  <gazebo reference="lms100_link">
    <sensor type="gpu_ray" name="head_hokuyo_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>50</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-2</min_angle>
            <max_angle>2</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>20.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
       
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_gpu_laser.so">
        <topicName>/rotation_laser/laserScan</topicName>
        <frameName>lms100_link</frameName>
      </plugin>
    </sensor>
  </gazebo>



  <!-- Base Link -->
  <link name="m3d_link">
    <collision>
      <origin xyz="0 0 ${box_height/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${box_depth} ${box_width} ${box_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${box_height/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${box_depth} ${box_width} ${box_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${box_height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (box_width*box_width + box_height*box_height)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (box_height*box_height + box_width*box_width)}" iyz="0.0"
	  izz="${mass / 12.0 * (box_width*box_width + box_width*box_width)}"/>
    </inertial>
  </link>

  <joint name="m3d_rot_laser_joint" type="continuous">
    <parent link="m3d_link"/>
    <child link="m3d_rot_laser_link"/>
    <origin xyz="-0.1 0 ${box_height+0.1}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- laser link -->
  <link name="m3d_rot_laser_link">

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.2 0.2 0.02"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="0.1" ixy="0.0" ixz="0.0"
	  iyy="0.1" iyz="0.0"
	  izz="0.1"/>
    </inertial>
    
  </link>
<joint name="m3d_lms100_link_joint" type="fixed">
 
    <origin xyz="0.0 0 0.04" rpy="0 -${PI/2} 0"/>
    <child link="lms100_link"/>
    <parent link="m3d_rot_laser_link"/>
    
  </joint>
  
  
<link name="lms100_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://m3dunit_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

  <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	  ixx="0.1" ixy="0.0" ixz="0.0"
	  iyy="0.1" iyz="0.0"
	  izz="0.1"/>
    </inertial>
    
  </link>


  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="m3d_rot_laser_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  </xacro:macro>
</robot>
